spring.datasource.url=jdbc:postgresql://db.gdfuuicqahbrssljutou.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Kireti@2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080