spring.datasource.url=jdbc:postgresql://dpg-d7dl1atckfvc73et6s90-a:5432/localserviceshub
spring.datasource.username=gokulpostgress
spring.datasource.password=wBlQk7RclHMWl0VV6qaUMvSfxMTtE0WS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080